### ISSUE TITLE
Make it possible to put the search sites in a submenu

### ISSUE THREAD

**Issue by Sopor** [maksis/airdcpp-search-sites#1]
Make it possible to put the search sites in a submenu as it was before it was removed from AirDC, `Search sites` or maybe make the user create a custom name for it...

If you have many search sites the context menu could get quite long.

**Comment by maksis** [comment]
Creating submenus isn't something that can currently be done by the extensions. You should rather report it for the application itself. If you are talking about the Windows GUI, maybe you should first try to add many sites and see what happens.

**Comment by Sopor** [comment]
I already have three (default). That is already too many.
